name: StationofDoom
version: 1.7
main: de.j.stationofdoom.main.Main
api-version: 1.16
load: STARTUP
authors: [ 12jking ]

commands:
  afk:
    description: Toggle AFK
  plversion:
    description: Shows you the pluginversion
  lag:
    description: Kick Players when lag
  sit:
    description:
  deathpoint:
    description: Gibt dir deinen Death Point
  voterestart:
    description: Vote für restarts
  customenchant:
    description: