name: CI
on: [push]
jobs:

  buildtools:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
      - uses: SpraxDev/Action-SpigotMC@v3
        with:
          # A comma-separated list of Spigot version that should be compiled
          # These values are later given to the BuildTools.jar as '--rev' argument
          #
          # Example: latest, 1.14.4, 1.8.8
          versions: latest # Optio
          # Should sources be generated?
          # If enabled, BuildTools is provided the '--generate-source' argument
          generateSrc: false # Optio
          # Should the documentation be generated?
          # If enabled, BuildTools is provided the '--generate-docs' argument
          generateDoc: false # Optio
          # Should we disable the BuildTools's Java-Version-Check?
          # If enabled, BuildTools is provided the '--disable-java-check' argument
          disableJavaCheck: false # Optio
          # Disables the check for existing files in the local maven repository
          # Normally, a version is skipped if it is already installed
          # in the local maven repository to speed up build time
          forceRun: false # Optio
          # The amount of builds allowed to run at the same time
          # Set to '-1' to use system's cpu core count
          threads: -1 # Optio
          # You can choose between different BuildTools to be used by this action
          # ~~'SpraxDev' is my fork of SpigotMC's that introduces some changes (https://github.com/SpraxDev/Spigot-BuildTools/#breaking-changes)~~
          # My (SpraxDev) provider is causing some builds to fail depending on the build environment
          # Available: SpraxDev, SpigotMC
          buildToolProvider: SpigotMC # Optional

  build:
    runs-on: ubuntu-latest
    needs: [buildtools]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
          cache: gradle
      - name: Cache 1.18.1 Maven package
        id: cacheCaves
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository/org/spigotmc/spigot/1.18.1-R0.1-SNAPSHOT/
            ~/.m2/repository/org/spigotmc/spigot-parent/
            ~/.m2/repository/org/spigotmc/minecraft-server/
          key: ${{ runner.os }}-spigot-1.18.1-all
          restore-keys: ${{ runner.os }}-spigot-1.18.1-all
      - name: Build with Gradle
        run: ./gradlew build